apiVersion: apps/v1
kind: Deployment
metadata:
  name: buykaro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: swarupsinh10/buykaro-frontend:latest
        ports:
        - containerPort: 3000
